name: Kali Mirror Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t kali-mirror .

    - name: Run Docker Container
      run: docker run -d --name kali-mirror-instance kali-mirror